/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.1.0

Source Server         : emr
Source Server Version : 110200
Source Host           : 127.0.0.1:1521
Source Schema         : EMR

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2016-08-15 13:32:42
*/


-- ----------------------------
-- Table structure for ZDINFO
-- ----------------------------
DROP TABLE "EMR"."ZDINFO";
CREATE TABLE "EMR"."ZDINFO" (
"JZXH" NUMBER(10) NULL ,
"LX" NUMBER(10) NOT NULL ,
"LR" NVARCHAR2(254) NULL ,
"ZYQK" NUMBER(10) NULL ,
"ICD_10" NVARCHAR2(100) NULL ,
"CREATE_ID" NUMBER(10) NOT NULL ,
"CREATE_TIME" DATE NOT NULL ,
"MODIFY_ID" NUMBER(10) NOT NULL ,
"MODIFY_TIME" DATE NOT NULL ,
"MXID" VARCHAR2(32 BYTE) NULL ,
"DIAGNOSTIC_ORDER1" NUMBER(10) NULL ,
"ZC_TYP" NUMBER(10) NULL ,
"ZC_NAM" NVARCHAR2(30) NULL ,
"BABY_ZYH" NVARCHAR2(32) NULL ,
"ZD_TYP" NVARCHAR2(2) DEFAULT '10'  NULL ,
"RYBQ" NUMBER(10) NULL ,
"ID" NVARCHAR2(32) NOT NULL ,
"BRID" NUMBER(10) NULL ,
"SYNC" CHAR(1 BYTE) NULL ,
"SSTREEID" VARCHAR2(32 BYTE) NULL,
"RELATIVEID" VARCHAR2(32) NULL
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "EMR"."ZDINFO"."ID" IS '主键';
COMMENT ON COLUMN "EMR"."ZDINFO"."BRID" IS '病人id，与病人入院信息关联';
COMMENT ON COLUMN "EMR"."ZDINFO"."SYNC" IS '是否同步';
COMMENT ON COLUMN "EMR"."ZDINFO"."RELATIVEID" IS '关联ID';

-- ----------------------------
-- Indexes structure for table ZDINFO
-- ----------------------------
CREATE INDEX "EMR"."IDX_ZDLR"
ON "EMR"."ZDINFO" ("LR" ASC)
LOGGING
VISIBLE;
CREATE INDEX "EMR"."INDEX_ZDINFO_JZXH"
ON "EMR"."ZDINFO" ("JZXH" ASC)
LOGGING
VISIBLE;
CREATE INDEX "EMR"."INDEX_ZDINFO_LX"
ON "EMR"."ZDINFO" ("LX" ASC)
LOGGING
VISIBLE;
CREATE INDEX "EMR"."INDEX_ZDINFO_LX_MXID"
ON "EMR"."ZDINFO" ("LX" ASC, "MXID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Triggers structure for table ZDINFO
-- ----------------------------
CREATE OR REPLACE TRIGGER "EMR"."TRIG_DEL_RYZD" BEFORE DELETE ON "EMR"."ZDINFO" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE WHEN (old.lx=320 or old.lx=310)
begin
       insert into zdinfo_bak(id,jzxh,lx,lr,icd_10,ordrow1,create_id,create_time,modify_id,modify_time,delete_time,zd_typ)
       values(:OLD.id,:OLD.jzxh,:OLD.lx,:OLD.lr,:OLD.icd_10,:OLD.diagnostic_order1,:OLD.create_id,:OLD.create_time,:OLD.modify_id,
       :OLD.modify_time,sysdate,:OLD.zd_typ);
end;
-- ----------------------------
-- Checks structure for table ZDINFO
-- ----------------------------
ALTER TABLE "EMR"."ZDINFO" ADD CHECK ("LX" IS NOT NULL);
ALTER TABLE "EMR"."ZDINFO" ADD CHECK ("CREATE_ID" IS NOT NULL);
ALTER TABLE "EMR"."ZDINFO" ADD CHECK ("CREATE_TIME" IS NOT NULL);
ALTER TABLE "EMR"."ZDINFO" ADD CHECK ("MODIFY_ID" IS NOT NULL);
ALTER TABLE "EMR"."ZDINFO" ADD CHECK ("MODIFY_TIME" IS NOT NULL);
ALTER TABLE "EMR"."ZDINFO" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "EMR"."ZDINFO" ADD CHECK ("LX" IS NOT NULL);
ALTER TABLE "EMR"."ZDINFO" ADD CHECK ("CREATE_ID" IS NOT NULL);
ALTER TABLE "EMR"."ZDINFO" ADD CHECK ("CREATE_TIME" IS NOT NULL);
ALTER TABLE "EMR"."ZDINFO" ADD CHECK ("MODIFY_ID" IS NOT NULL);
ALTER TABLE "EMR"."ZDINFO" ADD CHECK ("MODIFY_TIME" IS NOT NULL);
ALTER TABLE "EMR"."ZDINFO" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "EMR"."ZDINFO" ADD CHECK ("LX" IS NOT NULL);
ALTER TABLE "EMR"."ZDINFO" ADD CHECK ("CREATE_ID" IS NOT NULL);
ALTER TABLE "EMR"."ZDINFO" ADD CHECK ("CREATE_TIME" IS NOT NULL);
ALTER TABLE "EMR"."ZDINFO" ADD CHECK ("MODIFY_ID" IS NOT NULL);
ALTER TABLE "EMR"."ZDINFO" ADD CHECK ("MODIFY_TIME" IS NOT NULL);
ALTER TABLE "EMR"."ZDINFO" ADD CHECK ("LX" IS NOT NULL);
ALTER TABLE "EMR"."ZDINFO" ADD CHECK ("CREATE_ID" IS NOT NULL);
ALTER TABLE "EMR"."ZDINFO" ADD CHECK ("CREATE_TIME" IS NOT NULL);
ALTER TABLE "EMR"."ZDINFO" ADD CHECK ("MODIFY_ID" IS NOT NULL);
ALTER TABLE "EMR"."ZDINFO" ADD CHECK ("MODIFY_TIME" IS NOT NULL);
ALTER TABLE "EMR"."ZDINFO" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table ZDINFO
-- ----------------------------
ALTER TABLE "EMR"."ZDINFO" ADD PRIMARY KEY ("ID");
