DROP TABLE STAGE_FORM_STORAGE;
CREATE TABLE STAGE_FORM_STORAGE (
	ID VARCHAR2(32) NOT NULL, 
	KEY VARCHAR2(256), 
	CONTENT CLOB, 
	PRIMARY KEY (ID)
);

DROP TABLE FORM_TEMPLATE_STORAGE;
CREATE TABLE FORM_TEMPLATE_STORAGE (
	ID VARCHAR2(36) NOT NULL, 
	CODE VARCHAR2(256) NOT NULL, 
	CONTENT CLOB, 
	VERSION TIMESTAMP(6), 
	TITLE VARCHAR2(256), 
	PRIMARY KEY (ID)
);
